DROP TABLE USERS;
DROP TABLE INBOX;
DROP TABLE MESSAGE;
DROP TABLE GROUPS;
DROP TABLE CONTACTLIST;
DROP TABLE INBOXMESSAGES;
DROP TABLE INVITES;

CREATE TABLE INVITES(
        leaderId INT,
        userId INT,
        FOREIGN KEY(leaderId) REFERENCES USERS(userId),
        FOREIGN KEY(userId) REFERENCES USERS(userId)
);

CREATE TABLE GROUPS(
    groupId INT PRIMARY KEY AUTO_INCREMENT,
    leaderId INT,
    FOREIGN KEY(leaderId) REFERENCES USERS(userId)
); 
CREATE TABLE INBOX(
    inboxId INT PRIMARY KEY AUTO_INCREMENT,
    ownerId INT,
    FOREIGN KEY(ownerId) REFERENCES USERS(userId)
);
CREATE TABLE MESSAGE(
    msgId INT PRIMARY KEY AUTO_INCREMENT,
    msgType INT NOT NULL,
    title VARCHAR(128) NOT NULL,
    content VARCHAR(2048) NOT NULL,
    senderId INT,
    FOREIGN KEY(senderId) REFERENCES USERS(userId)
);
CREATE TABLE USERS(
    userID INT PRIMARY KEY AUTO_INCREMENT,
    password_hash VARCHAR(256) NOT NULL,
    first_name VARCHAR(64) NOT NULL,
    last_name VARCHAR(64) NOT NULL,
    faculty_number INT NOT NULL UNIQUE,
    number_theme INT NULL UNIQUE,
    member_of INT NULL,
    FOREIGN KEY(member_of) REFERENCES GROUPS(groupId)
);

CREATE TABLE CONTACTLIST(
	userId INT NOT NULL,
	contactId INT NOT NULL,
    FOREIGN KEY(userId) REFERENCES USERS(userId),
    FOREIGN KEY(contactId) REFERENCES USERS(userId)
);

CREATE TABLE INBOXMESSAGES(
	inboxId INT NOT NULL,
	msgId INT NOT NULL,
    FOREIGN KEY(inboxId) REFERENCES INBOX(inboxId),
    FOREIGN KEY(msgId) REFERENCES MESSAGE(msgId)
);
